accounts/urls.py
from django.urls import path
from accounts import views

app_name = "accounts"

urlpatterns = [
    path('login', views.user_login, name="login"),
    path('signup', views.user_signup, name="signup"),
    path('profile', views.user_profile, name="profile"),  
]

vishavant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from vishavant import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace="accounts"),),
    path('', include('website.urls', namespace="website"),),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,
                                                                                         document_root=settings.STATIC_ROOT)

website/urls.py
from django.urls import path
from website import views

app_name = "website"

urlpatterns = [
    path('', views.homepage, name='home'),
    path('projects/', views.display_projects, name='projects'),
    path('blogs/', views.display_blogs, name='blogs'),
    path('contact-me/', views.contact_me, name='contact-me'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(blank=True)
    pic = models.ImageField(blank=True, upload_to='user_profile_pic')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

website/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render

# Create your views here.

def user_login(request):
    return render(request, "accounts/user_login.html")


def user_signup(request):
    return render(request, "user_registration.html")


def user_logout(request):
    pass

def user_profile(request):
    return render(request, "accounts/user_profile.html")

website/views.py
from django.shortcuts import render

# Create your views here.


def homepage(request):
    return render(request, "website/homepage.html")


def display_projects(request):
    return render(request, "website/display_projects.html")


def display_blogs(request):
    return render(request, "website/display_blogs.html")


def contact_me(request):
    return render(request, "website/contact_me.html")

website/templates/website/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block page_title %}{% endblock page_title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'website/css/style.css' %}">
    {% block custom_css %}{% endblock custom_css %}
</head>
  <body>
    {% include 'website/navbar.html' %}

    {% block page_heading %}{% endblock page_heading %}

    {% block page_content %}
    
    {% endblock page_content %}

    
    {% comment %} {% include 'website/footer.html' %} {% endcomment %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
</body>
</html>

website/templates/website/contact_me.html
{% extends 'website/base.html' %}


{% block page_title %}contact{% endblock page_title %}


{% block page_content %}

<h1>I am contact page</h1>
{% endblock page_content %}

website/templates/website/display_blogs.html
{% extends 'website/base.html' %}

{% block page_title %}blogs{% endblock page_title %}


{% block page_content %}

<h1>This is blog page</h1>
{% endblock page_content %}

website/templates/website/display_projects.html
{% extends 'website/base.html' %}


{% block page_title %}projects{% endblock page_title %}

{% block page_content %}

<h1>I am project page</h1>
{% endblock page_content %}

website/templates/website/footer.html
<h3>I am Footer</h3>

website/templates/website/homepage.html
{% extends 'website/base.html' %}
{% load static %}

{% block page_title %}
home
{% endblock page_title %}


{% block page_heading %}



{% endblock page_heading %}


{% block page_content %}
<section class="hero-heading">
    <div class="container text-center hero-heading-text">
        <h1>Developer & Designer</h1>
        <h5>I code and design beautifully simple things</h5>
        <img src="{% static 'website\images\undraw_male_avatar_g98d.svg' %}" alt="">
    </div>
    <div class="container hero-image text-center">
        <img src="{% static 'website\images\Screenshot_20221216_110329 1.png' %}" alt="">
    </div>
</section>


{% endblock page_content %}

website/templates/website/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link " aria-current="page" href="{% url 'website:projects' %}">Pojects</a>
          </li>
          <li class="nav-item">
            <a class="nav-link " aria-current="page" href="{% url 'website:blogs' %}">Blogs</a>
          </li>
          <li class="nav-item">
            <a class="nav-link " aria-current="page" href="#">News</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'website:contact-me' %}">Contact Me</a>
          </li>
     
        </ul>
        <button class="btn btn-primary me-2">Login</button>
        <button class="btn btn-warning me-2">Signup</button>
        
      </div>
    </div>
  </nav>